# Run `travis lint` when changing this file to avoid breaking the build.
# Default JDK is really old: 1.8.0_31; Trusty's is less old: 1.8.0_51
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: false
dist: trusty

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r opentracing-contrib/java-globaltracer BINTRAY_USER=your_github_account
  - secure: "zxxgdEqZA+A5tAeNWIkbCuL9fg31QSR/7k56CQ+xPVepGR62DpJQa05sZ+e+d3FppUPo25yIOfsYdaq0kb9mZj9tlyVU/nm7AroMs9MjAHiFZWGef3GaczzTEPgBcRsKRn1qZ3Gm5y1LSn6b4liEyxcHkVexIuWDKgFz1MCqzBDkJp+FBm4l3ZUGFoNdd514JhxOv4a6gjWgLwxavlyHyLLE6je2I1f/fpczvpRKMIUUMoYZqpm8NbPu/Q9rA1sRA25SoclaJQx/l1pzFIdo3DqPNw29BNCSOoBm9QkcBmKkpPkBZ7E1q9tF/fUEqiW3VSgTTJcK7FHU5242f+6D8lsyxeV/5INTdC1IHW0O19KlLOA5cAINezZpWC0ZFIBy0dy6GjR/DRAjWuS+XRitg7dUYdcAl1slHkQkfJj3iXYlKs5W1KXbaVtVGaUasmhrSOoSwgscDL5VYnas8Mh3FmJQn+sHvE9VJhD0aFWh38Tck1nlUYdSz8tOS1/i3+TvmNMhpNsHTesr1U4+rzJAi5QSFzkQcAmxDaVc8Nw2EibIoB+2lkpP/4KHMG4Hjl1OZ7qPJvVEN3/BZnAfNvFAJpDg4sYKHk+eGjkDRItWlNOUEy1+eFaB2s7Sm8sdi10rj9TSCqcTFZui6+klmyfGmEjvclnUgp6jd5a2AqKJXK4="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "YgPkRx1jtfVyLQjwLtT9kIfYHBs7b1vJ5EwtOQ53lwifj0aoY/XF+JdfhPDj9ixV9qZiKjtCucTrKeB5baCxeb8wyMJ4R/MQSsR+XKQ4tXIE/d9PB+n+xBRWc3D5KDNSTi+nJNMb15eeK9StEwcAgw7/9YGofBDvNwucnqXmshof3QkPasDF8SscTpZ+X4VHDqJ/UUwH2wSuRgJwHgiPs5aSHwfkqIsdXXzMj6uplc+fvyP1M1Eso6UuuDuNRkFfUKyCIH9ihHxzwZ06l9xDycOMI23I/fGqqNH/cF/ITeWTmSnurOq30hmxD3ltlXdTbbO0kB3M7o+3fLlz9P37eedouhvEVMO7+nVS7HWWt4ie9rNQWyjkPkP/9A0HDxWAp9QAzs7NSwEdXCOofJWgdKc1LLtsVuXMJeWFPQ9a5L/XORKg28gBgoqtYqjRodrk6htjQdZqUsCsHQMw5MnHCgSwYBo/J/IWBuKJ28LSVahPvR5hUc32s1egVrO6IvHnpYjHXufyi0B5o4vXOjUkpi1DjRy2M9PpnzFl5Q+a4BOCeASi5jVjMChbNFZNEZWhoqrvdvZGBxQ5fScDs0LZ4WE+XuN/W8tQ0o0ALTk/c+o9+T6pcq382u9JXWPlR7qqs7LEQZ2IP7v5i3/D1kmQIHTl2L81585XsusCbLkHQUM="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "HqqEDOkQcH8KorLozk+NzCkTmPgzlhxNhjv3UhdT72fQD/OgKnP6MhsdpoGkeWmlBs1M68Zn8XWrn7oVawgwVEHF8SdxKOx+3K01LqAb2NW7KqtZpWbq8S1oLiWaPUIzP5vMKsptmEHqHWRh9FbRlsRwwDIjlG/JOTJufqCw2htjJJAbWD6pOaEIZtrQPk8QT7LDeNi2m5jCKwjhEgOJPGRXwwExqTrSP3CVo5WL5FVe6nORdJv15SaoSMf/+Rf+PiZhJmX2Aw0+6nZ5/j5rKEz7Hg574z9qqMGMPCx2hvaDM9HCVaIwVMG2VT6Shd7eF42k7l8m8MNXaF789NeUlZSVJFT4UZrTbOdaZJSo8VlTvzt5reQmJ6Hv15wvZyShho/Zi2BXscBUxTe4ZbjvCk9RyH8573vibcRP3oUgaypAoaWxJm8SWqi1+iAoe7II1Vipql3Rr7Dsi/2q/5r7bZ96YCnzPmvzuzTxhyF7mnV7vuhZ99JQ+0+BJC5b5ne4cQNkIjUCMvC9m1lVTJarKXhQNbOEV55Oq+pXoLLpq1HJeDvzsi7hao0HyyWTjAr03V81oSIlvu25nUsDgwxQuYW784E6W/MR1idlLPGmElcSlN0TSHAZ+XtyTlkdwtSA9uwN5/q/GERcOaTQWxU16pHsmuc2qIZ58/lA/QMzuUY="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "viLxK5I0dT7AZnYBs0Cw4A1iyUY9bCRRSnrRrqY5z9aYKO6Sh6EG0thwnt7ZReDREXV/I2hLyi4bwwH7Nu343GD+mes7p3cfiFEuuIDtbQ3W4ZeXeTvklghqBGugVKXwLz2eQlsbIEDLcAD8mwfIhPsJk7q0R75LP6BwjUrhXWaRBhAus/Nivnr5JWuvHhZSitRtoBQtC2bbl1mUNS6xLevgF3NYb31vmI4YQB8CAtMPcuIBDDStqazIFnf0neCMKrH2+EOWMnuaAGs7qtK6R4mQVmwb1Wxa+mDz1m0oc62J8GPABRi77Q3Pvx71OIooZuV+8/qcIIIKPFb7dDXrMQRjVXstWzYWIVRuv+Q4vkgj5Q1M2vVAAnw0XVNPqcV4QPcsnEV16XYJPdQE2NBQmEOwWBA1ciq4h1TMPdCCNFPWs6C6OYlFjVtt4+2a0H2Vq5xJcFVQjrqtlF/Pwfdi0XO/Z3Kpr8OCAaSLbBOjSBPNWFNUDMz2If5iRwqZ6wbRRov8gG74AW/g03LI2CY4M7bjwREkyf6pL0ZbaHFbyCUynGRvExInbVGTIHsFrUufM6IFh96+rFKn1/8E/5cZjOGLMfx6MVcM2uch+d3VuiNfXtg8Hu6IqKfepJz7VTPpSsZk8hkdEVPOR5aoVViSQ0lucSjJD7/RwmzqlcvlwQ4="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "HbXFDbLJKcY7rxZQqbR24EAlXcJhoqfKJ668OGNuV3dFTwz5ZMJUJb/NKHY32ok6fC3uRZHqBM4spWyCb27oj7usf8zk46U5uE/Gx2HTnUXBHtztc3qmZeJ2FfMrFk2MvYguLQ9ms+7+ppAVTHafXf8yjmtnqZYj8Ph6OaePolsFDzXe9wht8ufUsglojwkSFqmzzJEP6/FJ/1FTnDbDRIpUAWpurCgx2m/IIyoG9LapLU/xQARfzjWX0RegzytEvPS4e+lpYxGtFY6pBS0Mr++5Vefi3cx30SCRTwVInUmc8lWQFdkYU49ZyRR1p+OTI543e26EC3SoTBoKEA1RENEMANiqrevo/DAsOkeJCHXZjsP1QLJ61V57Xi07haLGSNa/eo8jdL3aR2eSFnsCYu+4uDz6LKQf3n+t+Isz04jDBRPk7GhVqIMY0rZP59VLWv1acqjW51x5PTHNZ8bp5MDBXF09B/nB5s/KcXjAa5uaPPl7RGrf2QCHxoAeuxCheWf3N4KUckckfFwDIC44uYJCGCb4LVsZ8UTa1jkol0EEH7HeJCAWcDomv/2iudp3MQ7nItIw+35CNV/Okf4sKJOd0d3vJ3fV0JiYchcDVH3DQGUA7e5mtrV3nhqEpD1iFpQLnKVHdekX5PIJovzD77dgi6b/TX/aOhbNcvTThCs="
