sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r org/repo BINTRAY_USER=your_github_account
  - secure: "zxxgdEqZA+A5tAeNWIkbCuL9fg31QSR/7k56CQ+xPVepGR62DpJQa05sZ+e+d3FppUPo25yIOfsYdaq0kb9mZj9tlyVU/nm7AroMs9MjAHiFZWGef3GaczzTEPgBcRsKRn1qZ3Gm5y1LSn6b4liEyxcHkVexIuWDKgFz1MCqzBDkJp+FBm4l3ZUGFoNdd514JhxOv4a6gjWgLwxavlyHyLLE6je2I1f/fpczvpRKMIUUMoYZqpm8NbPu/Q9rA1sRA25SoclaJQx/l1pzFIdo3DqPNw29BNCSOoBm9QkcBmKkpPkBZ7E1q9tF/fUEqiW3VSgTTJcK7FHU5242f+6D8lsyxeV/5INTdC1IHW0O19KlLOA5cAINezZpWC0ZFIBy0dy6GjR/DRAjWuS+XRitg7dUYdcAl1slHkQkfJj3iXYlKs5W1KXbaVtVGaUasmhrSOoSwgscDL5VYnas8Mh3FmJQn+sHvE9VJhD0aFWh38Tck1nlUYdSz8tOS1/i3+TvmNMhpNsHTesr1U4+rzJAi5QSFzkQcAmxDaVc8Nw2EibIoB+2lkpP/4KHMG4Hjl1OZ7qPJvVEN3/BZnAfNvFAJpDg4sYKHk+eGjkDRItWlNOUEy1+eFaB2s7Sm8sdi10rj9TSCqcTFZui6+klmyfGmEjvclnUgp6jd5a2AqKJXK4="
  # Ex. travis encrypt -r org/repo BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "YgPkRx1jtfVyLQjwLtT9kIfYHBs7b1vJ5EwtOQ53lwifj0aoY/XF+JdfhPDj9ixV9qZiKjtCucTrKeB5baCxeb8wyMJ4R/MQSsR+XKQ4tXIE/d9PB+n+xBRWc3D5KDNSTi+nJNMb15eeK9StEwcAgw7/9YGofBDvNwucnqXmshof3QkPasDF8SscTpZ+X4VHDqJ/UUwH2wSuRgJwHgiPs5aSHwfkqIsdXXzMj6uplc+fvyP1M1Eso6UuuDuNRkFfUKyCIH9ihHxzwZ06l9xDycOMI23I/fGqqNH/cF/ITeWTmSnurOq30hmxD3ltlXdTbbO0kB3M7o+3fLlz9P37eedouhvEVMO7+nVS7HWWt4ie9rNQWyjkPkP/9A0HDxWAp9QAzs7NSwEdXCOofJWgdKc1LLtsVuXMJeWFPQ9a5L/XORKg28gBgoqtYqjRodrk6htjQdZqUsCsHQMw5MnHCgSwYBo/J/IWBuKJ28LSVahPvR5hUc32s1egVrO6IvHnpYjHXufyi0B5o4vXOjUkpi1DjRy2M9PpnzFl5Q+a4BOCeASi5jVjMChbNFZNEZWhoqrvdvZGBxQ5fScDs0LZ4WE+XuN/W8tQ0o0ALTk/c+o9+T6pcq382u9JXWPlR7qqs7LEQZ2IP7v5i3/D1kmQIHTl2L81585XsusCbLkHQUM="
  # Ex. travis encrypt -r org/repo GH_USER=your_github_account
  - secure: "Fm2POxvDPjJng27bCLIlhR6UjQy2PVsUVVi3wuTvhyZKJAKk/bz9WxaEUin5K6O5DfD+t96vvicQV4T14/Cdk7FIVA4YluRUjUVssxyEREvxzrTjsABdtXRTrNk3d05Qix7wOssACwn8q9HN6SdZXnoWnzgZ/dzIQuoJjnMgJDZ6aW/bCijs9vRukcWoYIfln2OjJpEHzEzy9roJD5PWwwPltA+ZEOq2wrB4tgjYucoh/cMpNK+aepQ6WlP4bzkhSGyqQxiD526rlR31X/siO9VRbpeRGP++57Lgv056WtnXq92zSbDBNDD9kkJiHOHJeG2eD3BNUUo1IxP3KkHkt1sY1GCSxsdYeMmjkiG6WrzDyA9INE4sBJ/7cLCqYjGqN0mWKOtF6nrdkWsQj+GRKEU0wLftWeLkWKhzl4T3lur0RAEX1l7lZsTTWLRmmoY0XF5g+zPCkSAyu7FAsb8RaeQWAXwRWs7n1JUA5ADZpPEZvA2/QPMKxKi0eSMF3QJjsh0031q5cdOsYiVyoaeouJXIQbO0P6INselx5ZH8LQyXeMC5u8hC0Nck+w/SlNZroWxzAE0EkKNZcFLwd0uwqFqdPyijgdE+iLnAIbj6VZQ25MevC81qK1HK5f15ow1uzF+qkoWAYGY1UGtopBuQJisrV0veGkykc4EPXriHd7g="
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "IAK0xvepru66hGhF4l5r/oHVUfz8sg840rMZvmvkFTPSRJvhOY8wdGp72cDXbSCCuzBkfxm9m16ZfleYG1HLF46RvZAj7P61KecMJIS91PedpGYDpzJwqk/jU2NSYG0bsoRTzkiIA2O8G6kua7S4k4aA4vdujO/c5+M/T5IFIr2Gp6VlHuhgsgd7p2cwXheMJyOM7LfRhHEo+/g1viKqFqBxROSXt0YrZQ031Y1OwMuYWIzjJnZf/ExKoyFssz33gGN3sHd0ljhdtXaW/gCILT3PoqIGw88AhjGvjWkErQhPpT1avWbJlqdmK64etyUbiXcbEWtZDPm+KEnwqkgwiHUcY4AUI43aejXRJ2VVRnnVz/AotSJ71H6Nhp6B+AXp5G7dn75YUTevw9znEUs9p/IqEpUMikZj1fUWv4/XZiQEEUEKlfQdkN23OJZwhIuD/1J1JfbLf35duMLeNUmHliosz3cDjMgvGkJqlU2pWR1s8RmjTSvctlDW6apGC4Zgtt27WikXMLLvvv96Hz2EIiZ+zHorVkRUS9xHQXVeF7fLBzphoZ2/67UIERTsZHZ5FzzoMTdN+Vu6IZnO9WK3FLitffYNthXRsRmhg7t3tQNuALmheo7huTtC2KBgFx99okgxvACvcZlqwqqc9PbY6N9cmtcP6g0L3TDrX2Wrk9I="
  # Ex. travis encrypt -r org/repo SONATYPE_USER=your_sonatype_account
  - secure: "j1XtaCBCfg3Bajh+ZcyhXa5nbWGqwaJYtvdTiBetD0yiemOMe1sk9KZj/KP7UVyPQxRwxMhm3AZu08hZrfdsVnzZpsv5/9VYqZJFjrRa74oSZKrVtBP2eK0/gIWUihUwUFxBUXt6oGVSNTD4mOtXKwxmq277fjFIMKFeSTFR4xUPAsOXprYPMLDo8Pt3wgFZR+0RsR2nc/A3KAXjx20UtKPW+vFxsUD5yLhko9winUGVWHPfqYEqQVHerWDB5uTmG8JK/dI1lHkvwb/cEGEcwZuUFSzV5Nkfq6gOhnPM/ex3IXgfdGnh9rnCZJYfyQkOG6+JasDW0sRqFnwE1f0mWpzGPLxnRG+QFS/LxxdSm43OcwEvID8PtyptntPQHZNP/vSePyZIE0UlNOWigNyEG4xWCjyB6u8kFkJfL5QN5+MdudCagBe1cvwMrWF7kovdJjjsjdx53it1NzVK2prk/WnZv+h9Ux6IBBFRj6hEJD5aqZYKhWu04KT51hiSZNxsQRl+LyfQb39Fba+9iALpcCLHEkC5DRBOM2sWy1fva71BRVzAxVeI/5BU4b2xOmigIXb1ybQYofUR6U0aLFrwvafFV5NpzfhvgVPGBJt/jKw0GrVHSmgaz9q61JJjff17aTnEvZRUglM8C3UViQ9ElL2v6yOnPV+WHAjRenHv88c="
  # Ex. travis encrypt -r org/repo SONATYPE_PASSWORD=your_sonatype_password
  - secure: "qxoHS8h7aoY/ycjEFTWrZR19cEcBGl0Rc2kve5P6RbpWJbacqE4YZniipAs1Jq6mNyKrpHwYB7yS+GzW3UT6+WQfmgD6xNhF2FaxYsngZ5O9N66eSxwGba8fLHPlcVvlGd1FVAe+zmudvVQ6XbZFjHBGmRhWxNuGHmUzA5lfMYLyE1EtC5cSRHnkHs1Iaocl5mjrYxLp6x7TPiPEd07MI2PMUXqXTp15R0GHeqaMpYfiBUn9vj4+A09lTGcxtVftyVyH0JruTHzRpAupRmePcvp/vFIfIQYPpbDyCcJ2A2RSPZM1iSnGWC1GcLIrG+ovQzvhjioXjCNOjb9kwYEimaY6zy8qIXwQUjG8ioBl24IqpD48bY3r7gXUH7eIfM411DJBkRY6cwMeW33waomtOkLy5Zwr0sYRBlf4y1oIQVd2EE22fjyuq6tfsucRNGBNX62zBxs9pHeYdpF0mRs8mrbeRD7hNNjmo8z+6Q6NCHNBph5zhxn8Tba85sm9CYXBe0XEb2/tfv6JFqL8xmSaaXbmi6GesQV9kXOWPIb2FaWZNqCHlr1hFE41+rPXjgX9tMt2ec2s7wTvXFzXXVBsp8CehRMp24SjwNCdFQ0Bk6DLpu9mj+VH5y/KbNEW8z0VE7oh9eT9uskFR1Inmfgpzk01oGfMAdWywzmAIGoLAWc="
